services:
  db:
    image: postgres:17-alpine
    container_name: ecommerce-db
    environment:
      POSTGRES_USER: shop_user
      POSTGRES_PASSWORD: shop_password
      POSTGRES_DB: shop_db
    ports:
      - "5436:5432"
    volumes:
      - ecommerce_db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ecommerce-redis
    ports:
      - "6383:6379"
    volumes:
      - ecommerce_redis_data:/data

volumes:
  ecommerce_db_data:
  ecommerce_redis_data:
